In [42]:
import pandas as pd
from geopandas import GeoDataFrame
import shapely.geometry
from shapely.geometry import Point

In [3]:
df = pd.read_csv('data/missingMigrants.csv')
med = df.loc[(df['Region of Incident'] == 'Mediterranean') & df['Information Reliability'].isin(['Verified'])]
med.head()

,Web ID,Region of Incident,Reported Date,Reported Year,Reported Month,Number Dead,Number Missing,Total Dead and Missing,Number of survivors,Number of Female,Number of Male,Number of Children,Cause of death,Location Description,Information Source,Location,Information Reliability,Migrant Route,URL,UNSD Geographical Grouping
2,44086,Mediterranean,"January 09, 2018",2018,Jan,NaN,100.0,100,16.0,NaN,NaN,NaN,Presumed drowning,"Off the coast of Al Khums, Libya","IOM Libya, Reuters, AFP, Libyan Navy","33.461246171967, 14.630447728125",Verified,Central Mediterranean,"http://bit.ly/2FnDv26, http://reut.rs/2CJiA7F,...",Uncategorized
5,44080,Mediterranean,"January 07, 2018",2018,Jan,2.0,10.0,12,270.0,2.0,NaN,NaN,Presumed drowning,"Off the coast of Garabuli, Libya",IOM Libya,"32.983002330562, 13.768852058594",Verified,Central Mediterranean,http://bit.ly/2Enoaxc,Uncategorized
6,44079,Mediterranean,"January 06, 2018",2018,Jan,8.0,56.0,64,86.0,6.0,2.0,5.0,Unknown,Unspecified location off the coast of Libya,"IOM Italy, SOS Méditerranée, MSF Sea","34.078380455797, 13.268242596875",Verified,Central Mediterranean,"http://bbc.in/2Ej8fzR, http://bit.ly/2D7iXdi, ...",Uncategorized
7,44078,Mediterranean,"January 05, 2018",2018,Jan,4.0,NaN,4,4.0,NaN,NaN,NaN,Presumed drowning,"Near Tanger-Med cargo port, 40km east of Tangi...",Salvamento Marítimo,"35.880538323659, -5.519505224414",Verified,Western Mediterranean,"http://bit.ly/2qG7miM, http://bit.ly/2mcXFDW",Uncategorized
21,44071,Mediterranean,"December 22, 2017",2017,Dec,1.0,NaN,1,NaN,NaN,NaN,NaN,Presumed drowning,"Near Tripoli, Libya",IOM Libya,"32.926409826220, 13.113060712109",Verified,Central Mediterranean,NaN,Uncategorized

In [23]:
x = lambda row: float(row.split(",")[0])
y = lambda row: float(row.split(",")[1])

In [35]:
med['latitude'] = med['Location'].map(x)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
med['longitude'] = med['Location'].map(y)

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [37]:
med.head()

,Web ID,Region of Incident,Reported Date,Reported Year,Reported Month,Number Dead,Number Missing,Total Dead and Missing,Number of survivors,Number of Female,...,Location,Information Reliability,Migrant Route,URL,UNSD Geographical Grouping,x,y,geometry,latitude,longitude
2,44086,Mediterranean,"January 09, 2018",2018,Jan,NaN,100.0,100,16.0,NaN,...,"33.461246171967, 14.630447728125",Verified,Central Mediterranean,"http://bit.ly/2FnDv26, http://reut.rs/2CJiA7F,...",Uncategorized,33.461246,14.630448,POINT (14 33),33.461246,14.630448
5,44080,Mediterranean,"January 07, 2018",2018,Jan,2.0,10.0,12,270.0,2.0,...,"32.983002330562, 13.768852058594",Verified,Central Mediterranean,http://bit.ly/2Enoaxc,Uncategorized,32.983002,13.768852,POINT (13 32),32.983002,13.768852
6,44079,Mediterranean,"January 06, 2018",2018,Jan,8.0,56.0,64,86.0,6.0,...,"34.078380455797, 13.268242596875",Verified,Central Mediterranean,"http://bbc.in/2Ej8fzR, http://bit.ly/2D7iXdi, ...",Uncategorized,34.078380,13.268243,POINT (13 34),34.078380,13.268243
7,44078,Mediterranean,"January 05, 2018",2018,Jan,4.0,NaN,4,4.0,NaN,...,"35.880538323659, -5.519505224414",Verified,Western Mediterranean,"http://bit.ly/2qG7miM, http://bit.ly/2mcXFDW",Uncategorized,35.880538,-5.519505,POINT (-5 35),35.880538,-5.519505
21,44071,Mediterranean,"December 22, 2017",2017,Dec,1.0,NaN,1,NaN,NaN,...,"32.926409826220, 13.113060712109",Verified,Central Mediterranean,NaN,Uncategorized,32.926410,13.113061,POINT (13 32),32.926410,13.113061

In [39]:
geometry = [Point(xy) for xy in zip((med.longitude).astype(int), (med.latitude).astype(int))]
med = med.drop(['latitude', 'longitude'], axis=1)
crs = {'init': 'epsg:4326'}
gdf = GeoDataFrame(med, crs=crs, geometry=geometry)

In [43]:
gdf.to_file("mediterraneum.geojson", driver='GeoJSON')

In [44]:
! ls

data                  dataprocess.ipynb     mediterraneum.geojson

In [41]:
med.head()

,Web ID,Region of Incident,Reported Date,Reported Year,Reported Month,Number Dead,Number Missing,Total Dead and Missing,Number of survivors,Number of Female,...,Location Description,Information Source,Location,Information Reliability,Migrant Route,URL,UNSD Geographical Grouping,x,y,geometry
2,44086,Mediterranean,"January 09, 2018",2018,Jan,NaN,100.0,100,16.0,NaN,...,"Off the coast of Al Khums, Libya","IOM Libya, Reuters, AFP, Libyan Navy","33.461246171967, 14.630447728125",Verified,Central Mediterranean,"http://bit.ly/2FnDv26, http://reut.rs/2CJiA7F,...",Uncategorized,33.461246,14.630448,POINT (14 33)
5,44080,Mediterranean,"January 07, 2018",2018,Jan,2.0,10.0,12,270.0,2.0,...,"Off the coast of Garabuli, Libya",IOM Libya,"32.983002330562, 13.768852058594",Verified,Central Mediterranean,http://bit.ly/2Enoaxc,Uncategorized,32.983002,13.768852,POINT (13 32)
6,44079,Mediterranean,"January 06, 2018",2018,Jan,8.0,56.0,64,86.0,6.0,...,Unspecified location off the coast of Libya,"IOM Italy, SOS Méditerranée, MSF Sea","34.078380455797, 13.268242596875",Verified,Central Mediterranean,"http://bbc.in/2Ej8fzR, http://bit.ly/2D7iXdi, ...",Uncategorized,34.078380,13.268243,POINT (13 34)
7,44078,Mediterranean,"January 05, 2018",2018,Jan,4.0,NaN,4,4.0,NaN,...,"Near Tanger-Med cargo port, 40km east of Tangi...",Salvamento Marítimo,"35.880538323659, -5.519505224414",Verified,Western Mediterranean,"http://bit.ly/2qG7miM, http://bit.ly/2mcXFDW",Uncategorized,35.880538,-5.519505,POINT (-5 35)
21,44071,Mediterranean,"December 22, 2017",2017,Dec,1.0,NaN,1,NaN,NaN,...,"Near Tripoli, Libya",IOM Libya,"32.926409826220, 13.113060712109",Verified,Central Mediterranean,NaN,Uncategorized,32.926410,13.113061,POINT (13 32)